spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:jvn1orcl  # 오라클 DB 주소
    username: jvn1orcl  # 오라클 DB 사용자 이름
    password: 19990610  # 오라클 DB 비밀번호
    driver-class-name: oracle.jdbc.OracleDriver  # 오라클 JDBC 드라이버
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect  # Hibernate 오라클 Dialect
    hibernate:
      ddl-auto: update  # 필요하면 create, update, validate 설정 가능